/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Game API
 * OpenAPI spec version: 0.1.0
 */

export interface GameResponse {
  id: string;
  player_name: string;
  status: string;
  photo_count: number;
  ghost_description?: string;
  avatar_url?: string | null;
  cleared_items?: string[];
  created_at: string;
  updated_at: string;
}
