/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Game API
 * OpenAPI spec version: 0.1.0
 */

export interface GameResponse {
  id: string;
  player_name: string;
  status: string;
  current_chapter: number;
  current_phase: string;
  unlocked_hints: number[];
  photo_count: number;
  created_at: string;
  updated_at: string;
}
