/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Game API
 * OpenAPI spec version: 0.1.0
 */

export interface GameUpdateRequest {
  status?: string | null;
  current_chapter?: number | null;
  current_phase?: string | null;
}
