/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Game API
 * OpenAPI spec version: 0.1.0
 */

export interface PhotoResponse {
  id: string;
  game_id: string;
  original_url: string;
  ghost_url?: string | null;
  ghost_gesture?: string | null;
  ghost_message?: string | null;
  detected_item?: string | null;
  created_at: string;
}
