/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Game API
 * OpenAPI spec version: 0.1.0
 */

export interface ScenarioChapter {
  chapter: number;
  title: string;
  story: string;
  hints: string[];
  answer_keyword: string;
  ghost_prompt_template: string;
}
