/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Game API
 * OpenAPI spec version: 0.1.0
 */

export interface TurnResponse {
  game_id: string;
  photo_id: string;
  original_url: string;
  detected_item?: string | null;
  ghost_url?: string | null;
  ghost_message?: string | null;
  cleared_items: string[];
  items_remaining: string[];
  game_status: string;
  game_solved: boolean;
  hint_message: string;
  message: string;
}
