/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Game API
 * OpenAPI spec version: 0.1.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BodyPlayTurnGameGameIdTurnPost,
  BodyUploadFileStorageUploadPost,
  BodyUploadPhotoGameGameIdPhotosPost,
  GameCreateRequest,
  GameResponse,
  GameUpdateRequest,
  GenerateImageRequest,
  GenerateImageResponse,
  GenerateRequest,
  GenerateResponse,
  PhotoListResponse,
  PhotoResponse,
  TurnResponse
} from '../model';

import type { HintMessage } from '../model/scenarioChapter';




  export const getGameAPI = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * @summary Create Game
 */
const createGameGamePost = (
    gameCreateRequest: GameCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GameResponse>> => {
    return axiosInstance.post(
      `/game/`,
      gameCreateRequest,options
    );
  }

/**
 * @summary Get Game
 */
const getGameGameGameIdGet = (
    gameId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GameResponse>> => {
    return axiosInstance.get(
      `/game/${gameId}`,options
    );
  }

/**
 * @summary Update Game
 */
const updateGameGameGameIdPatch = (
    gameId: string,
    gameUpdateRequest: GameUpdateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GameResponse>> => {
    return axiosInstance.patch(
      `/game/${gameId}`,
      gameUpdateRequest,options
    );
  }

/**
 * @summary Generate
 */
const generateGeminiGeneratePost = (
    generateRequest: GenerateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GenerateResponse>> => {
    return axiosInstance.post(
      `/gemini/generate`,
      generateRequest,options
    );
  }

/**
 * @summary Generate Image
 */
const generateImageGeminiGenerateImagePost = (
    generateImageRequest: GenerateImageRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GenerateImageResponse>> => {
    return axiosInstance.post(
      `/gemini/generate-image`,
      generateImageRequest,options
    );
  }

/**
 * @summary Upload File
 */
const uploadFileStorageUploadPost = (
    bodyUploadFileStorageUploadPost: BodyUploadFileStorageUploadPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {const formData = new FormData();
formData.append(`file`, bodyUploadFileStorageUploadPost.file);

    return axiosInstance.post(
      `/storage/upload`,
      formData,options
    );
  }

/**
 * @summary Get Signed Url
 */
const getSignedUrlStorageUrlPathGet = (
    path: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/storage/url/${path}`,options
    );
  }

/**
 * @summary Upload Photo
 */
const uploadPhotoGameGameIdPhotosPost = (
    gameId: string,
    bodyUploadPhotoGameGameIdPhotosPost: BodyUploadPhotoGameGameIdPhotosPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PhotoResponse>> => {const formData = new FormData();
formData.append(`file`, bodyUploadPhotoGameGameIdPhotosPost.file);

    return axiosInstance.post(
      `/game/${gameId}/photos/`,
      formData,options
    );
  }

/**
 * @summary List Photos
 */
const listPhotosGameGameIdPhotosGet = (
    gameId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PhotoListResponse>> => {
    return axiosInstance.get(
      `/game/${gameId}/photos/`,options
    );
  }

/**
 * @summary Get Photo
 */
const getPhotoGameGameIdPhotosPhotoIdGet = (
    gameId: string,
    photoId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PhotoResponse>> => {
    return axiosInstance.get(
      `/game/${gameId}/photos/${photoId}`,options
    );
  }

/**
 * @summary Generate Ghost
 */
const generateGhostGameGameIdPhotosPhotoIdGhostPost = (
    gameId: string,
    photoId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PhotoResponse>> => {
    return axiosInstance.post(
      `/game/${gameId}/photos/${photoId}/ghost`,undefined,options
    );
  }

/**
 * @summary List Hint Messages
 */
const listHintMessagesScenarioHintsGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HintMessage[]>> => {
    return axiosInstance.get(
      `/scenario/hints`,options
    );
  }

/**
 * @summary Get Hint Message
 */
const getHintMessageScenarioHintsItemGet = (
    item: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<HintMessage>> => {
    return axiosInstance.get(
      `/scenario/hints/${item}`,options
    );
  }

/**
 * @summary Play Turn
 */
const playTurnGameGameIdTurnPost = (
    gameId: string,
    bodyPlayTurnGameGameIdTurnPost: BodyPlayTurnGameGameIdTurnPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TurnResponse>> => {const formData = new FormData();
formData.append(`file`, bodyPlayTurnGameGameIdTurnPost.file);

    return axiosInstance.post(
      `/game/${gameId}/turn`,
      formData,options
    );
  }

/**
 * @summary Health
 */
const healthHealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

return {createGameGamePost,getGameGameGameIdGet,updateGameGameGameIdPatch,generateGeminiGeneratePost,generateImageGeminiGenerateImagePost,uploadFileStorageUploadPost,getSignedUrlStorageUrlPathGet,uploadPhotoGameGameIdPhotosPost,listPhotosGameGameIdPhotosGet,getPhotoGameGameIdPhotosPhotoIdGet,generateGhostGameGameIdPhotosPhotoIdGhostPost,listHintMessagesScenarioHintsGet,getHintMessageScenarioHintsItemGet,playTurnGameGameIdTurnPost,healthHealthGet}};
export type CreateGameGamePostResult = AxiosResponse<GameResponse>
export type GetGameGameGameIdGetResult = AxiosResponse<GameResponse>
export type UpdateGameGameGameIdPatchResult = AxiosResponse<GameResponse>
export type GenerateGeminiGeneratePostResult = AxiosResponse<GenerateResponse>
export type GenerateImageGeminiGenerateImagePostResult = AxiosResponse<GenerateImageResponse>
export type UploadFileStorageUploadPostResult = AxiosResponse<unknown>
export type GetSignedUrlStorageUrlPathGetResult = AxiosResponse<unknown>
export type UploadPhotoGameGameIdPhotosPostResult = AxiosResponse<PhotoResponse>
export type ListPhotosGameGameIdPhotosGetResult = AxiosResponse<PhotoListResponse>
export type GetPhotoGameGameIdPhotosPhotoIdGetResult = AxiosResponse<PhotoResponse>
export type GenerateGhostGameGameIdPhotosPhotoIdGhostPostResult = AxiosResponse<PhotoResponse>
export type ListHintMessagesScenarioHintsGetResult = AxiosResponse<HintMessage[]>
export type GetHintMessageScenarioHintsItemGetResult = AxiosResponse<HintMessage>
export type PlayTurnGameGameIdTurnPostResult = AxiosResponse<TurnResponse>
export type HealthHealthGetResult = AxiosResponse<unknown>
