/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Game API
 * OpenAPI spec version: 0.1.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BodyUploadFileStorageUploadPost,
  GameCreateRequest,
  GameResponse
} from '../model';




  export const getGameAPI = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * @summary Create Game
 */
const createGameGamePost = (
    gameCreateRequest: GameCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GameResponse>> => {
    return axiosInstance.post(
      `/game/`,
      gameCreateRequest,options
    );
  }

/**
 * @summary Get Game
 */
const getGameGameGameIdGet = (
    gameId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GameResponse>> => {
    return axiosInstance.get(
      `/game/${gameId}`,options
    );
  }

/**
 * @summary Upload File
 */
const uploadFileStorageUploadPost = (
    bodyUploadFileStorageUploadPost: BodyUploadFileStorageUploadPost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {const formData = new FormData();
formData.append(`file`, bodyUploadFileStorageUploadPost.file);

    return axiosInstance.post(
      `/storage/upload`,
      formData,options
    );
  }

/**
 * @summary Get Signed Url
 */
const getSignedUrlStorageUrlPathGet = (
    path: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/storage/url/${path}`,options
    );
  }

/**
 * @summary Health
 */
const healthHealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

return {createGameGamePost,getGameGameGameIdGet,uploadFileStorageUploadPost,getSignedUrlStorageUrlPathGet,healthHealthGet}};
export type CreateGameGamePostResult = AxiosResponse<GameResponse>
export type GetGameGameGameIdGetResult = AxiosResponse<GameResponse>
export type UploadFileStorageUploadPostResult = AxiosResponse<unknown>
export type GetSignedUrlStorageUrlPathGetResult = AxiosResponse<unknown>
export type HealthHealthGetResult = AxiosResponse<unknown>
